[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# When working with private keys avoid .env file and use the following code in the terminal
# cast wallet import NAME_OF_FILE --interactive
# Then paste in the private key
# create a password for the wallet you called "NAME_OF_FILE"
#
# So when running the deployment script on localhost or testnet it would look something like this,
# forge script script/ContractScriptName.s.sol:ContractScriptName --rpc-url http://127.0.0.1:8545 --broadcast --sender PUBLIC_ADDRESS_OF_ACCOUNT_YOU_IMPORTED --account NAME_OF_FILE

# jq '.abi' out/ContractName.sol/ContractName.json > ContractNameABI.json

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x1'
dictionary_weight = 40
include_storage = true
include_push_bytes = true
extra_output = ["storageLayout", "metadata"]

[invariant]
runs = 256
depth = 32
fail_on_revert = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
# example:
# zksync = "https://mainnet.era.zksync.io"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/N-xInl4-MvlVwtClZjoMxNqFyiAP4PcZ"

[etherscan]
sepolia = { key = "XK1YC9BH1K44AQ5AKTFJPXMEITQRW64KH8" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
